language: node_js
node_js: 12

branches:
  only:
    - develop

before_script: npm install

matrix:
  fast_finish: true
  include:
  - name: npm test
    install: npm install -g typescript@3 mocha@6
    script: npm test
  - name: tslint
    install: npm install -g typescript@3 tslint@5
    script: tslint -c tslint.json "src/**/*.ts"
