language: node_js
node_js: 10

branches:
  only:
    - master

before_script: npm install

matrix:
  fast_finish: true
  include:
  - name: npm test
    install: npm install -g typescript@3 mocha@5.2
    script: npm test
  - name: tslint
    install: npm install -g typescript@3 tslint@5.11
    script: tslint -c tslint.json "src/**/*.ts"
